In [81]:
import numpy as np

def reduceToUpper(A, b):
    # A is square nxn matrx
    # b is nx1 vector
    assert len(A.shape) == len(b.shape) == 2
    assert A.shape[0] == A.shape[1]
    assert b.shape[1] == 1
    A = A.astype(np.float64)
    b = b.astype(np.float64)
    
    N = A.shape[0]
    for i in range(N-1):
        for j in range(i+1, N):
            # partial pivoting
            pivot = np.argmax(np.abs(A[i:, i]))
            # if pivot!= 0:
            #     print("swapping")
            temp = A[i, :].copy()
            A[i, :] = A[i+pivot, :]
            A[i+pivot, :] = temp
            
            temp = b[i, 0].copy()
            b[i, 0] = b[i+pivot, 0]
            b[i+pivot, 0] = temp
            
            coeff = -A[j, i]/A[i, i]
            A[j, :] = A[j, :] + coeff*A[i, :]
            b[j, 0] = b[j, 0] + coeff*b[i, 0]
            # print(A)
            # print(b)
    return A, b


In [82]:
def backsubstitution(A, b):
    assert b.shape[1] == 1
    assert len(A.shape) == 2
    assert A.shape[1] == b.shape[0]
    
    #A: upper-traingular matrix
    #b: column vector
    A = A.astype(np.float64)
    b = b.astype(np.float64)
    
    N = b.shape[0]
    x = np.zeros((N, 1))
    
    for i in range(N-1, -1, -1):
        sum = 0
        for j in range(i, N):
            sum += A[i, j]*x[j, 0]
        # sum = A[i, :]*x[i:]
        x[i, 0] = (b[i, 0] - sum)/A[i, i]
          
    return x

In [83]:
def solve(A,b):
    A, b = reduceToUpper(A,b)
    return backsubstitution(A,b)

In [ ]:
import time
time_taken = {}
for size in [10, 100, 1000, 10000]:
    A = np.random.randn(size, size)
    b = np.random.randn(size, 1)
    start = time.time()
    solution = solve(A,b)
    end = time.time()
    time_taken[size] = end-start

    
    

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Suppose you already have time_taken filled
# Example: time_taken = {20:0.001, 50:0.004, 100:0.02, 500:0.5}

sizes = np.array(list(time_taken.keys()))
times = np.array(list(time_taken.values()))

plt.figure(figsize=(6,4))

# x-axis as log(size), y as time in seconds
plt.plot(np.log(sizes), times, marker='o', label="time (sec)")

# If you prefer ms, just multiply times by 1000
# plt.plot(np.log(sizes), times*1000, marker='o', label="time (ms)")

plt.xlabel("log(matrix size)")
plt.ylabel("Computation time (seconds)")
plt.title("Solve(A, b) timing vs log(size)")
plt.grid(True)
plt.legend()
plt.show()

In [69]:
A = np.array([[2, 1, 1],
              [1, 1, 2],
              [1, 1, 3]])
b = np.array([[2], [3], [6]])

In [70]:
reduceToUpper(A, b)

array([[2. , 1. , 1. ],
       [0. , 0.5, 1.5],
       [0. , 0. , 1. ]])

In [71]:
A = np.array([[3, -13,  9,  3],
              [-6,  4,  1, 18],
              [6, -2,  2,  4],
              [12, -8,  6, 10]])

b = np.array([-19, -34, 16, 26]).reshape(-1, 1)
reduceToUpper(A,b)

array([[ 12. ,  -8. ,   6. ,  10. ],
       [  0. , -11. ,   7.5,   0.5],
       [  0. ,   0. ,   4. ,  23. ],
       [  0. ,   0. ,   0. ,  -3. ]])

In [72]:
A = np.array([[1,      0,    0,   1000],
              [50,     2,    3,    100],
              [2,      1,    1,  1e-2],
              [1e-2,   1,    1,      2]])

b = np.array([1, 1, 1, 1]).reshape(-1,1)
reduceToUpper(A,b)

array([[ 5.00000000e+01,  2.00000000e+00,  3.00000000e+00,
         1.00000000e+02],
       [ 0.00000000e+00,  9.99600000e-01,  9.99400000e-01,
         1.98000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.98159264e-02,
        -5.81232893e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.46944695e-18,
         1.00100000e+03]])